os: linux

dist: focal

git:
  depth: 1

cache: false

language: python

python: 3.9

install:
- pip install --upgrade pip
- pip install -Iv pelican==4.5.0
- pip install pelican markdown

script:
- pelican content -s pelicanconf.py --fatal warnings --debug
