os:
- linux
- windows

dist: jammy

git:
  depth: 1

cache: false

language: rust

rust: stable

install:
- if [ "$TRAVIS_OS_NAME" == "windows" ]; then choco install python; fi
- if [ "$TRAVIS_OS_NAME" == "windows" ]; then refreshenv; fi
# - curl https://sh.rustup.rs -sSf | sh -s -- -y
# - source "$HOME/.cargo/env"
- cargo install stork-search --locked
- pip install --upgrade pip
- pip install pelican markdown pelican-search

script:
- stork --version
- pelican content -s pelicanconf.py --fatal warnings --debug
