os: linux

dist: jemmy

git:
  depth: 1

cache: false

language: python

python: 3.10

install:
- curl https://sh.rustup.rs -sSf | sh -s -- -y
- source "$HOME/.cargo/env"
- cargo install stork-search --locked
- pip install --upgrade pip
- pip install pelican markdown pelican-search

script:
- stork --help
- pelican content -s pelicanconf.py --fatal warnings --debug
