git:
  depth: 1

cache: false

language: rust

rust: stable

jobs:
  include:
    - name: "Ubuntu 22.04 LTS (Jammy Jellyfish)"
      os: linux
      dist: jammy
    - name: "Windows Server 1809"
      os: windows
      env:
        - PATH=/c/Python310:/c/Python310/Scripts:$PATH
      before_install: "choco install python"

install:
- python -m pip install --upgrade pip
- pip install pelican markdown pelican-search
# - curl https://sh.rustup.rs -sSf | sh -s -- -y
# - source "$HOME/.cargo/env"
- cargo install stork-search --locked
# - pip install --upgrade pip
# - pip install pelican markdown pelican-search

script:
- stork --version
- pelican content -s pelicanconf.py --fatal warnings --debug
