git:
  depth: 1

dist: focal

language: python

python: 3.8

install:
- pip install --upgrade pip
- pip install markdown pelican

script:
- pelican content -s pelicanconf.py --fatal warnings --verbose
-  grep -E "<title>.*</title>" output/Kira-Goddess.html