# Depth
git:
  depth: 1

dist: xenial
language: python

python: 3.7

install:
  - pip install --upgrade pip
  - pip install gitpython markdown pelican

script:
  - pelican content -s pelicanconf.py --debug --fatal warnings