os: windows
# - linux

# dist: jammy

git:
  depth: 1

cache: false

language: rust

rust: stable

env:
- PATH=/c/Python310:/c/Python310/Scripts:$PATH

install:
- choco install python
- python -m pip install --upgrade pip
- pip install pelican markdown pelican-search
# - curl https://sh.rustup.rs -sSf | sh -s -- -y
# - source "$HOME/.cargo/env"
- cargo install stork-search --locked
# - pip install --upgrade pip
# - pip install pelican markdown pelican-search

script:
- stork --version
- pelican content -s pelicanconf.py --fatal warnings --debug
