version: 2.1

jobs:
  build:
    machine:
      image: "windows-server-2022-gui:current"
      resource_class: windows.medium
    steps:
    - checkout
    - run: pip install pelican markdown pelican-search
    - run: choco install rust
    - run: cargo install stork-search --locked
    - run: stork --version
    - run: pelican content -s pelicanconf.py --fatal warnings --debug
    - run: dir output
